"""
Model Comparison: BM25 Keyword Baseline vs. Semantic Vector Search.
Runs both evaluation harnesses and produces a side-by-side Markdown report.
"""
import json
import time
from pathlib import Path

from src.config import (
    BASELINE_METRICS_PATH,
    SEMANTIC_METRICS_PATH,
    COMPARISON_REPORT_PATH,
)
from src.baseline.evaluate_baseline import evaluate_baseline
from src.semantic.evaluate_semantic import evaluate_semantic


def _delta(semantic_val: float, base_val: float) -> str:
    """Return a formatted delta string with a +/- sign and arrow."""
    diff = semantic_val - base_val
    arrow = "▲" if diff >= 0 else "▼"
    return f"{arrow} {abs(diff):.4f}"


def run_comparison() -> None:
    """Run both evaluators and write a Markdown comparison report."""
    print("=" * 60)
    print("  Running BM25 Baseline Evaluation...")
    print("=" * 60)
    baseline = evaluate_baseline()

    print("\n" + "=" * 60)
    print("  Running Semantic Vector Search Evaluation...")
    print("=" * 60)
    semantic = evaluate_semantic()

    # ── Print console comparison table ────────────────────────────────
    print("\n\n" + "=" * 60)
    print("  📊  SIDE-BY-SIDE COMPARISON")
    print("=" * 60)

    metrics_to_compare = [
        ("MRR", "mrr"),
        ("MAP", "map"),
    ]

    print(f"{'Metric':<20} {'BM25':>10} {'Semantic':>10} {'Δ (Semantic-BM25)':>16}")
    print("-" * 60)
    for label, key in metrics_to_compare:
        b = baseline.get(key, 0.0)
        d = semantic.get(key, 0.0)
        print(f"{label:<20} {b:>10.4f} {d:>10.4f} {_delta(d, b):>16}")

    all_ks = sorted(
        set(baseline["metrics"].keys()) | set(semantic["metrics"].keys())
    )
    for k_key in all_ks:
        for metric_suffix in ["precision", "recall", "ndcg"]:
            b_val = baseline["metrics"].get(k_key, {}).get(
                f"{metric_suffix}@{k_key.split('=')[1]}", 0.0
            )
            d_val = semantic["metrics"].get(k_key, {}).get(
                f"{metric_suffix}@{k_key.split('=')[1]}", 0.0
            )
            label = f"{metric_suffix.upper()}@{k_key.split('=')[1]}"
            print(
                f"{label:<20} {b_val:>10.4f} {d_val:>10.4f} {_delta(d_val, b_val):>16}"
            )

    print("-" * 60)
    print(
        f"{'Latency p50 (ms)':<20} "
        f"{baseline['latency_ms']['p50']:>10.2f} "
        f"{semantic['latency_ms']['p50']:>10.2f}"
    )
    print(
        f"{'Latency p95 (ms)':<20} "
        f"{baseline['latency_ms']['p95']:>10.2f} "
        f"{semantic['latency_ms']['p95']:>10.2f}"
    )
    print("=" * 60)

    # ── Write Markdown report ──────────────────────────────────────────
    COMPARISON_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# Semantic Product Search — Model Comparison Report",
        f"\n> Generated: {timestamp}",
        "\n## Models Evaluated",
        f"- **Baseline**: {baseline['model']}",
        f"- **Semantic**: {semantic['model']}",
        f"- **Queries**: {baseline['total_queries']}",
        "\n## Summary Metrics",
        "",
        "| Metric | BM25 Baseline | Semantic Search | Δ (Semantic − BM25) |",
        "|--------|:-------------:|:------------:|:----------------:|",
    ]

    for label, key in metrics_to_compare:
        b = baseline.get(key, 0.0)
        d = semantic.get(key, 0.0)
        lines.append(f"| {label} | {b:.4f} | {d:.4f} | {_delta(d, b)} |")

    for k_key in all_ks:
        k_num = k_key.split("=")[1]
        for metric_suffix in ["precision", "recall", "ndcg"]:
            b_val = baseline["metrics"].get(k_key, {}).get(
                f"{metric_suffix}@{k_num}", 0.0
            )
            d_val = semantic["metrics"].get(k_key, {}).get(
                f"{metric_suffix}@{k_num}", 0.0
            )
            label = f"{metric_suffix.capitalize()}@{k_num}"
            lines.append(
                f"| {label} | {b_val:.4f} | {d_val:.4f} | {_delta(d_val, b_val)} |"
            )

    lines += [
        "\n## Latency",
        "",
        "| Metric | BM25 Baseline | Semantic Search |",
        "|--------|:-------------:|:------------:|",
        f"| p50 (ms) | {baseline['latency_ms']['p50']:.2f} | {semantic['latency_ms']['p50']:.2f} |",
        f"| p95 (ms) | {baseline['latency_ms']['p95']:.2f} | {semantic['latency_ms']['p95']:.2f} |",
        "\n---",
        "\n*Report auto-generated by `src/compare_models.py`*",
    ]

    with open(COMPARISON_REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n✅  Comparison report saved → {COMPARISON_REPORT_PATH}")


if __name__ == "__main__":
    run_comparison()
